#!/usr/bin/env python3
"""
check_phase_gate.py — Verify PRAE phase gate conditions

Exit codes:
  0  All gate conditions pass (or already approved)
  1  Gate conditions not met
  2  File missing or malformed

Usage:
  python3 tools/check_phase_gate.py --project-dir <path> [--phase 0|1|2|3]
  python3 tools/check_phase_gate.py --project-dir <path> --check-approved
"""
from __future__ import annotations
import argparse
import os
import re
import sys
from pathlib import Path

import yaml

sys.path.insert(0, os.path.dirname(__file__))
from _cli import run_action
from _gate_utils import collapse_text, gate_payload, summarize_violations
from _phase_docs import PHASE_NAME_TO_NUM
from _registry import (
    get_cycle_label,
    get_phase_override,
    get_recorded_phase,
    load_registry as _shared_load_registry,
)
from check_contracts import run_check
from check_research_gate import ResearchGateError, evaluate_research_gate
from _output import check_item


class PhaseGateError(RuntimeError):
    """Raised when phase gate artifacts are missing or malformed."""


PHASE_DIRS = {phase_num: phase_name for phase_name, phase_num in PHASE_NAME_TO_NUM.items()}
PHASE_GATE_SECTIONS = [
    "## 1. Current Phase State",
    "## 2. Gate Conditions — Item-by-Item Check",
    "## 3. Evidence Summary",
    "## 4. Risks and Open Items",
    "## 5. Recommendation",
    "## 6. Pending Human Approval",
]
PHASE_REQUIRED_CHECKLIST_ITEMS = {
    0: [
        "All type=infrastructure tracks state = LOCKED",
        "Every LOCKED track has contracts.yaml",
        "Every LOCKED track has MODULE_SPEC.md",
        "Every LOCKED track passes the PDAE M3 gate (recorded in TRACK_LOG.md)",
        "check_contracts.py passes for all infrastructure contracts",
    ],
    1: [
        "≥1 research track state = ACTIVE (has a positive signal)",
        "All research tracks still EXPLORING have a clear keep-or-drop recommendation (continue / KILL / merge)",
        "Every ACTIVE track passes the Research Gate check",
    ],
    2: [
        "All formerly ACTIVE research tracks have a clear terminal-state recommendation",
        "At least one track is judged GRADUATED (otherwise consider KILLing the whole project)",
        "All GRADUATED candidates pass the Research Gate and Contracts Gate",
        "All GRADUATED candidates have a final-conclusion section in TRACK_LOG.md",
    ],
}


def load_registry(project_dir: str) -> dict:
    try:
        return _shared_load_registry(project_dir, error_cls=PhaseGateError)
    except Exception as exc:
        raise PhaseGateError(str(exc)) from exc


def _normalize_checklist_text(text: str) -> str:
    normalized = text.replace("`", "")
    normalized = normalized.replace("（", "(").replace("）", ")")
    normalized = re.sub(r"\s+", " ", normalized)
    return normalized.strip()

def _extract_checklist_statuses(content: str) -> dict[str, bool]:
    checklist_section = re.search(r"## 2\. Gate Conditions — Item-by-Item Check\n(.*?)(?=\n##|\Z)", content, re.DOTALL)
    if not checklist_section:
        return {}

    statuses: dict[str, bool] = {}
    for line in checklist_section.group(1).splitlines():
        match = re.match(r"\s*-\s*\[([xX ])\]\s*(.+?)\s*$", line)
        if not match:
            continue
        statuses[_normalize_checklist_text(match.group(2))] = match.group(1).lower() == "x"
    return statuses


def _validate_phase_gate_document(gate_path: str, expected_from_phase: int | None,
                                  registry: dict | None = None) -> tuple[list[dict], str]:
    with open(gate_path, encoding="utf-8") as f:
        content = f.read()

    checks: list[dict] = []
    if registry is not None:
        expected_cycle = get_cycle_label(registry)
        cycle_ok = re.search(rf"\*\*Research Cycle\*\*:\s*{re.escape(expected_cycle)}", content) is not None
        checks.append(check_item("PHASE_GATE research cycle is correct", cycle_ok, expected_cycle))

    if expected_from_phase is not None and expected_from_phase in {0, 1, 2}:
        expected_title = f"# Phase {expected_from_phase} → Phase {expected_from_phase + 1} Gate Analysis"
        checks.append(check_item("PHASE_GATE title is correct", expected_title in content, expected_title))

        expected_target = PHASE_DIRS[expected_from_phase + 1]
        target_ok = re.search(rf"\*\*Target Phase\*\*:\s*{re.escape(expected_target)}", content) is not None
        checks.append(check_item("PHASE_GATE target phase is correct", target_ok, expected_target))
    else:
        title_ok = re.search(r"^# Phase \d+ → Phase \d+ Gate Analysis$", content, re.MULTILINE) is not None
        checks.append(check_item("PHASE_GATE title format is correct", title_ok))

    generated_date_ok = re.search(r"\*\*Generated\*\*:\s*\d{4}-\d{2}-\d{2}", content) is not None
    checks.append(check_item("PHASE_GATE has a generated date", generated_date_ok))

    generated_by_ok = re.search(r"\*\*Generated by\*\*:\s*AI", content) is not None
    checks.append(check_item("PHASE_GATE has a generated-by field", generated_by_ok))

    for section in PHASE_GATE_SECTIONS:
        checks.append(check_item(f"PHASE_GATE contains section: {section}", section in content, section))

    checklist_section = re.search(r"## 2\. Gate Conditions — Item-by-Item Check\n(.*?)(?=\n##|\Z)", content, re.DOTALL)
    has_checkbox = bool(checklist_section and re.search(r"^- \[[xX ]\]\s+", checklist_section.group(1), re.MULTILINE))
    checks.append(check_item("PHASE_GATE has a checklist", has_checkbox, "Section 2 must have at least one [ ] / [x] item"))
    if expected_from_phase in PHASE_REQUIRED_CHECKLIST_ITEMS and checklist_section:
        normalized_section = _normalize_checklist_text(checklist_section.group(1))
        for item in PHASE_REQUIRED_CHECKLIST_ITEMS[expected_from_phase]:
            normalized_item = _normalize_checklist_text(item)
            checks.append(check_item(
                f"PHASE_GATE contains required gate item: {normalized_item}",
                normalized_item in normalized_section,
                item,
            ))

    recommendation_ok = re.search(r"\*\*Recommended Action\*\*:\s*(Advance|Do not advance yet)", content) is not None
    checks.append(check_item("PHASE_GATE has a recommended action", recommendation_ok))

    reason_ok = re.search(r"\*\*Rationale\*\*:\s*\S+", content) is not None
    checks.append(check_item("PHASE_GATE has a rationale", reason_ok))

    for field in ("APPROVED", "APPROVER", "APPROVED_AT", "COMMENT"):
        field_ok = re.search(rf"^{field}:\s*.*$", content, re.MULTILINE) is not None
        checks.append(check_item(f"PHASE_GATE contains field: {field}", field_ok, field))

    return checks, content


def _run_contract_gate(project_dir: str, track: dict) -> dict:
    track_id = track["id"]
    contracts_rel = track.get("contracts", "")
    if not contracts_rel:
        return check_item(f"{track_id}: check_contracts passes", False, "contracts field not filled in")

    src_dir = Path(project_dir) / "src"
    if not src_dir.is_dir():
        return check_item(f"{track_id}: check_contracts passes", False, f"src directory does not exist: {src_dir}")

    contracts_path = Path(project_dir) / contracts_rel
    if not contracts_path.exists():
        return check_item(f"{track_id}: check_contracts passes", False, str(contracts_path))

    try:
        with open(contracts_path, encoding="utf-8") as f:
            contract_data = yaml.safe_load(f)
    except (OSError, yaml.YAMLError) as exc:
        return check_item(f"{track_id}: check_contracts passes", False, f"contracts failed to parse: {exc}")
    if contract_data is not None and not isinstance(contract_data, dict):
        return check_item(f"{track_id}: check_contracts passes", False, "contracts top level must be a mapping")

    violations = run_check(contracts_path, [src_dir])
    if violations.has_immutable() or violations.has_critical():
        return check_item(f"{track_id}: check_contracts passes", False,
                          summarize_violations(track_id, violations))

    detail = "No blocking contract violations"
    if violations.has_need_review():
        detail = summarize_violations(track_id, violations)
    return check_item(f"{track_id}: check_contracts passes", True, detail)


def _run_research_gate(project_dir: str, track_id: str) -> dict:
    try:
        evaluation = evaluate_research_gate(project_dir, track_id)
    except ResearchGateError as exc:
        return check_item(f"{track_id}: Research Gate passes", False, collapse_text(str(exc)))

    failed_checks = [c["name"] for c in evaluation["checks"] if not c.get("passed")]
    detail = evaluation["summary"]
    if failed_checks:
        detail += f"; failed: {', '.join(failed_checks[:3])}"
        if len(failed_checks) > 3:
            detail += "..."
    latest_exp_id = evaluation.get("data", {}).get("latest_exp_id")
    if latest_exp_id:
        detail += f"; latest_exp={latest_exp_id}"

    return check_item(f"{track_id}: Research Gate passes", evaluation["passed"], detail)


def _evaluate_phase_0_to_1(project_dir: str, registry: dict) -> dict:
    checks: list[dict] = []
    infra_tracks = [t for t in registry.get("tracks", []) if t.get("type") == "infrastructure"]
    gate_conditions = {item: False for item in PHASE_REQUIRED_CHECKLIST_ITEMS[0]}

    if not infra_tracks:
        checks.append(check_item("At least one infrastructure track", False, "no infrastructure-type tracks in track_registry.yaml"))
        return {"checks": checks, "gate_conditions": gate_conditions, "summary": "No infrastructure tracks"}

    state_results: list[bool] = []
    contracts_results: list[bool] = []
    spec_results: list[bool] = []
    pdae_results: list[bool] = []
    contract_gate_results: list[bool] = []

    for t in infra_tracks:
        tid = t["id"]
        state = t.get("state", "")

        locked = state == "LOCKED"
        state_results.append(locked)
        checks.append(check_item(f"{tid}: state=LOCKED", locked, f"state={state}"))

        contracts_path = t.get("contracts", "")
        contracts_exists = bool(contracts_path) and os.path.exists(os.path.join(project_dir, contracts_path))
        contracts_results.append(contracts_exists)
        checks.append(check_item(f"{tid}: contracts.yaml exists", contracts_exists, contracts_path or "field not filled in"))

        spec_path = t.get("module_spec", "")
        spec_exists = bool(spec_path) and os.path.exists(os.path.join(project_dir, spec_path))
        spec_results.append(spec_exists)
        checks.append(check_item(f"{tid}: MODULE_SPEC.md exists", spec_exists, spec_path or "field not filled in"))

        contract_gate_check = _run_contract_gate(project_dir, t)
        contract_gate_results.append(contract_gate_check["passed"])
        checks.append(contract_gate_check)

        track_log = os.path.join(project_dir, "prae", "phases", "phase_00_infra", "tracks", tid, "TRACK_LOG.md")
        log_exists = os.path.exists(track_log)
        checks.append(check_item(f"{tid}: TRACK_LOG.md exists", log_exists))

        has_pdae_record = False
        if log_exists:
            with open(track_log, encoding="utf-8") as f:
                log_content = f.read()
            has_pdae_record = "PDAE" in log_content or "M3" in log_content or "LOCKED" in log_content
        pdae_results.append(has_pdae_record)
        checks.append(check_item(
            f"{tid}: TRACK_LOG has a PDAE/LOCKED record",
            has_pdae_record,
            "no PDAE, M3, or LOCKED related record found in TRACK_LOG.md",
        ))

    gate_conditions[PHASE_REQUIRED_CHECKLIST_ITEMS[0][0]] = all(state_results)
    gate_conditions[PHASE_REQUIRED_CHECKLIST_ITEMS[0][1]] = all(contracts_results)
    gate_conditions[PHASE_REQUIRED_CHECKLIST_ITEMS[0][2]] = all(spec_results)
    gate_conditions[PHASE_REQUIRED_CHECKLIST_ITEMS[0][3]] = all(pdae_results)
    gate_conditions[PHASE_REQUIRED_CHECKLIST_ITEMS[0][4]] = all(contract_gate_results)

    for item in PHASE_REQUIRED_CHECKLIST_ITEMS[0]:
        checks.append(check_item(f"Gate condition: {item}", gate_conditions[item]))

    payload = gate_payload("Phase 0→1 gate", checks)
    payload["gate_conditions"] = gate_conditions
    return payload


def _evaluate_phase_1_to_2(project_dir: str, registry: dict) -> dict:
    checks: list[dict] = []
    research_tracks = [t for t in registry.get("tracks", []) if t.get("type") == "research"]
    gate_conditions = {item: False for item in PHASE_REQUIRED_CHECKLIST_ITEMS[1]}

    has_active = any(t.get("state") == "ACTIVE" for t in research_tracks)
    checks.append(check_item("At least 1 research track state=ACTIVE", has_active,
                              "all research tracks are still EXPLORING" if not has_active else ""))

    exploring_decisions: list[bool] = []
    active_research_gate: list[bool] = []

    for t in research_tracks:
        tid = t["id"]
        state = t.get("state", "")

        if state == "EXPLORING":
            track_log = os.path.join(project_dir, "prae", "phases", "phase_01_research", "tracks", tid, "TRACK_LOG.md")
            log_exists = os.path.exists(track_log)
            if log_exists:
                with open(track_log, encoding="utf-8") as f:
                    log_content = f.read()
                has_decision = "Decision Log" in log_content and len(
                    [l for l in log_content.splitlines() if "KILL" in l or "continue" in l or "MERGE" in l]
                ) > 0
                exploring_decisions.append(has_decision)
                checks.append(check_item(
                    f"{tid}: EXPLORING track has a keep-or-drop recommendation",
                    has_decision,
                    "no KILL/continue/MERGE recommendation found in TRACK_LOG.md Decision Log",
                ))
            else:
                exploring_decisions.append(False)
                checks.append(check_item(f"{tid}: TRACK_LOG.md exists", False, track_log))

        if state == "ACTIVE":
            exp_count = t.get("experiments", 0)
            checks.append(check_item(f"{tid}: has at least 1 experiment", exp_count >= 1, f"experiments={exp_count}"))
            research_gate_check = _run_research_gate(project_dir, tid)
            active_research_gate.append(research_gate_check["passed"])
            checks.append(research_gate_check)

    gate_conditions[PHASE_REQUIRED_CHECKLIST_ITEMS[1][0]] = has_active
    gate_conditions[PHASE_REQUIRED_CHECKLIST_ITEMS[1][1]] = bool(exploring_decisions) and all(exploring_decisions) if any(
        t.get("state") == "EXPLORING" for t in research_tracks
    ) else True
    gate_conditions[PHASE_REQUIRED_CHECKLIST_ITEMS[1][2]] = has_active and bool(active_research_gate) and all(active_research_gate)

    for item in PHASE_REQUIRED_CHECKLIST_ITEMS[1]:
        checks.append(check_item(f"Gate condition: {item}", gate_conditions[item]))

    payload = gate_payload("Phase 1→2 gate", checks)
    payload["gate_conditions"] = gate_conditions
    return payload


def _evaluate_phase_2_to_3(project_dir: str, registry: dict) -> dict:
    checks: list[dict] = []
    research_tracks = [t for t in registry.get("tracks", []) if t.get("type") == "research"]
    gate_conditions = {item: False for item in PHASE_REQUIRED_CHECKLIST_ITEMS[2]}

    active_tracks = [t for t in research_tracks if t.get("state") == "ACTIVE"]
    graduated_tracks = [t for t in research_tracks if t.get("state") == "GRADUATED"]

    has_graduated = len(graduated_tracks) >= 1
    checks.append(check_item("At least 1 track judged GRADUATED", has_graduated,
                              "no GRADUATED tracks; consider whether to terminate the whole project"))

    no_active_remaining = len(active_tracks) == 0
    checks.append(check_item("All research tracks have a terminal state (no ACTIVE remaining)", no_active_remaining,
                              f"{len(active_tracks)} tracks are still ACTIVE: "
                              f"{', '.join(t['id'] for t in active_tracks)}" if active_tracks else ""))

    graduated_research_gate: list[bool] = []
    graduated_final_logs: list[bool] = []
    for t in graduated_tracks:
        tid = t["id"]
        track_log_path = os.path.join(project_dir, "prae", "phases", "phase_02_validation", "tracks", tid, "TRACK_LOG.md")
        if not os.path.exists(track_log_path):
            graduated_final_logs.append(False)
            checks.append(check_item(f"{tid}: TRACK_LOG.md exists", False, track_log_path))
            continue

        with open(track_log_path, encoding="utf-8") as f:
            log_content = f.read()
        has_final = "GRADUATED" in log_content
        graduated_final_logs.append(has_final)
        checks.append(check_item(f"{tid}: TRACK_LOG has a final-conclusion section", has_final))

        research_gate_check = _run_research_gate(project_dir, tid)
        graduated_research_gate.append(research_gate_check["passed"])
        checks.append(research_gate_check)

    gate_conditions[PHASE_REQUIRED_CHECKLIST_ITEMS[2][0]] = no_active_remaining
    gate_conditions[PHASE_REQUIRED_CHECKLIST_ITEMS[2][1]] = has_graduated
    gate_conditions[PHASE_REQUIRED_CHECKLIST_ITEMS[2][2]] = has_graduated and bool(graduated_research_gate) and all(graduated_research_gate)
    gate_conditions[PHASE_REQUIRED_CHECKLIST_ITEMS[2][3]] = has_graduated and bool(graduated_final_logs) and all(graduated_final_logs)

    for item in PHASE_REQUIRED_CHECKLIST_ITEMS[2]:
        checks.append(check_item(f"Gate condition: {item}", gate_conditions[item]))

    payload = gate_payload("Phase 2→3 gate", checks)
    payload["gate_conditions"] = gate_conditions
    return payload


def evaluate_approval(project_dir: str, registry: dict) -> dict:
    override = get_phase_override(registry)
    if override:
        raise PhaseGateError(
            "current_phase_override is in effect; the regular PHASE_GATE / advance-phase flow is paused. Please complete the exception handling and remove the override first"
        )

    current = get_recorded_phase(registry, "")
    gate_path = os.path.join(project_dir, "prae", "phases", current, "PHASE_GATE.md")
    if not os.path.exists(gate_path):
        raise PhaseGateError(f"PHASE_GATE.md does not exist: {gate_path}")

    expected_from_phase = PHASE_NAME_TO_NUM.get(current)
    checks, content = _validate_phase_gate_document(gate_path, expected_from_phase, registry)

    m = re.search(r"^APPROVED:\s*(yes|no|pending)\s*$", content, re.MULTILINE)
    approved_val = m.group(1) if m else "not found"
    approved_yes = approved_val == "yes"
    checks.append(check_item("APPROVED: yes", approved_yes, f"current value={approved_val}"))

    approver_match = re.search(r"^APPROVER:\s*(.*)$", content, re.MULTILINE)
    approver = approver_match.group(1).strip() if approver_match else ""
    checks.append(check_item("APPROVER is filled in", bool(approver) if approved_yes else True,
                             approver or "APPROVER is empty"))

    approved_at_match = re.search(r"^APPROVED_AT:\s*(.*)$", content, re.MULTILINE)
    approved_at = approved_at_match.group(1).strip() if approved_at_match else ""
    date_ok = re.fullmatch(r"\d{4}-\d{2}-\d{2}", approved_at) is not None
    checks.append(check_item("APPROVED_AT format is correct", date_ok if approved_yes else True,
                             approved_at or "APPROVED_AT is empty"))

    if approved_yes and expected_from_phase in {0, 1, 2}:
        if expected_from_phase == 0:
            evaluation = _evaluate_phase_0_to_1(project_dir, registry)
        elif expected_from_phase == 1:
            evaluation = _evaluate_phase_1_to_2(project_dir, registry)
        else:
            evaluation = _evaluate_phase_2_to_3(project_dir, registry)

        actual_conditions = evaluation["gate_conditions"]
        checklist_statuses = _extract_checklist_statuses(content)
        all_actual_pass = all(actual_conditions.values())
        checks.append(check_item("All actual gate conditions pass when APPROVED", all_actual_pass, evaluation["summary"]))

        for item in PHASE_REQUIRED_CHECKLIST_ITEMS[expected_from_phase]:
            normalized_item = _normalize_checklist_text(item)
            recorded = checklist_statuses.get(normalized_item)
            actual = actual_conditions[item]
            if recorded is None:
                continue
            checks.append(check_item(
                f"PHASE_GATE checkbox status matches: {normalized_item}",
                recorded == actual,
                f"document={'[x]' if recorded else '[ ]'} actual={'[x]' if actual else '[ ]'}",
            ))

    passed = all(c["passed"] for c in checks)
    return {
        "passed": passed,
        "summary": f"Approval status: {approved_val}",
        "checks": checks,
        "data": {
            "current_phase": current,
            "gate_path": gate_path,
            "approved": approved_val,
            "approver": approver,
            "approved_at": approved_at,
        },
    }


def evaluate_phase_gate(project_dir: str, phase_num: int | None, check_approved: bool) -> dict:
    registry = load_registry(project_dir)
    override = get_phase_override(registry)
    if override:
        raise PhaseGateError(
            "current_phase_override is in effect; the regular Phase Gate check is paused. Please complete the exception handling and remove the override first"
        )

    current = get_recorded_phase(registry, "")

    if check_approved:
        return evaluate_approval(project_dir, registry)

    effective_phase = phase_num
    if effective_phase is None:
        effective_phase = PHASE_NAME_TO_NUM.get(current, -1)
        if effective_phase == -1:
            raise PhaseGateError(f"Cannot infer phase number from current_phase={current}; please specify with --phase")

    if effective_phase == 0:
        return _evaluate_phase_0_to_1(project_dir, registry)
    if effective_phase == 1:
        return _evaluate_phase_1_to_2(project_dir, registry)
    if effective_phase == 2:
        return _evaluate_phase_2_to_3(project_dir, registry)
    raise PhaseGateError(f"Unsupported phase number: {effective_phase}")


def main() -> None:
    parser = argparse.ArgumentParser(description="Check PRAE phase-gate conditions")
    parser.add_argument("--project-dir", required=True, help="Research project root directory")
    parser.add_argument("--phase", type=int, choices=[0, 1, 2], default=None,
                        help="Which phase-advance gate to check (0=Phase0->1, 1=Phase1->2, 2=Phase2->3)")
    parser.add_argument("--check-approved", action="store_true",
                        help="Check whether the current phase's PHASE_GATE.md is APPROVED: yes")
    args = parser.parse_args()
    run_action(
        lambda: evaluate_phase_gate(args.project_dir, args.phase, args.check_approved),
        PhaseGateError,
    )


if __name__ == "__main__":
    main()
