"""Unit tests for check_phase_gate.py."""
from __future__ import annotations
import json
import subprocess
import sys
from pathlib import Path

import pytest

TOOL = Path(__file__).parent.parent.parent / "tools" / "check_phase_gate.py"
PHASE_CHECKLIST_ITEMS = {
    0: [
        "All type=infrastructure tracks state = LOCKED",
        "Every LOCKED track has contracts.yaml",
        "Every LOCKED track has MODULE_SPEC.md",
        "Every LOCKED track passes the PDAE M3 gate (recorded in TRACK_LOG.md)",
        "check_contracts.py passes for all infrastructure contracts",
    ],
    1: [
        "≥1 research track state = ACTIVE (has a positive signal)",
        "All research tracks still EXPLORING have a clear keep-or-drop recommendation (continue / KILL / merge)",
        "Every ACTIVE track passes the Research Gate check",
    ],
    2: [
        "All formerly ACTIVE research tracks have a clear terminal-state recommendation",
        "At least one track is judged GRADUATED (otherwise consider KILLing the whole project)",
        "All GRADUATED candidates pass the Research Gate and Contracts Gate",
        "All GRADUATED candidates have a final-conclusion section in TRACK_LOG.md",
    ],
}


def run_tool(project_dir: str, extra_args: list[str] | None = None) -> tuple[int, dict]:
    args = [sys.executable, str(TOOL), "--project-dir", project_dir] + (extra_args or [])
    proc = subprocess.run(args, capture_output=True, text=True)
    try:
        output = json.loads(proc.stdout)
    except json.JSONDecodeError:
        output = {"raw": proc.stdout, "stderr": proc.stderr}
    return proc.returncode, output


def set_current_phase(project_dir: Path, phase_name: str) -> None:
    import yaml

    reg = project_dir / "prae" / "track_registry.yaml"
    with open(reg) as f:
        registry = yaml.safe_load(f)
    registry["current_phase"] = phase_name
    with open(reg, "w") as f:
        yaml.dump(registry, f, allow_unicode=True)


def set_phase_override(project_dir: Path, phase_name: str) -> None:
    import yaml

    reg = project_dir / "prae" / "track_registry.yaml"
    with open(reg) as f:
        registry = yaml.safe_load(f)
    registry["current_phase_override"] = phase_name
    with open(reg, "w") as f:
        yaml.dump(registry, f, allow_unicode=True)


def make_valid_phase_gate_doc(from_phase: int, to_phase: int, target_phase: str, approved: str,
                              *, drop_checklist_item: str | None = None,
                              unchecked_items: set[str] | None = None,
                              cycle_label: str = "cycle_1") -> str:
    approved_at = "2026-04-20" if approved == "yes" else ""
    approver = "maintainer" if approved == "yes" else ""
    unchecked_items = unchecked_items or set()
    checklist_items = [
        item for item in PHASE_CHECKLIST_ITEMS[from_phase]
        if item != drop_checklist_item
    ]
    checklist = "\n".join(
        f"- [{' ' if item in unchecked_items else 'x'}] {item}" for item in checklist_items
    )
    return (
        f"# Phase {from_phase} → Phase {to_phase} Gate Analysis\n\n"
        f"**Research Cycle**: {cycle_label}\n"
        f"**Generated**: 2026-04-20\n"
        f"**Generated by**: AI (Analyst role)\n"
        f"**Target Phase**: {target_phase}\n\n"
        "## 1. Current Phase State\n"
        "- infra_data_v1: LOCKED\n\n"
        "## 2. Gate Conditions — Item-by-Item Check\n"
        f"{checklist}\n\n"
        "## 3. Evidence Summary\n"
        "- Key evidence\n\n"
        "## 4. Risks and Open Items\n"
        "- None\n\n"
        "## 5. Recommendation\n"
        "**Recommended Action**: Advance\n"
        "**Rationale**: conditions satisfied\n\n"
        "## 6. Pending Human Approval\n"
        f"APPROVED: {approved}\n"
        f"APPROVER: {approver}\n"
        f"APPROVED_AT: {approved_at}\n"
        "COMMENT: \n"
    )


def make_phase1_active_track(project_dir: Path, *, with_research_artifacts: bool) -> None:
    import yaml

    reg = project_dir / "prae" / "track_registry.yaml"
    with open(reg) as f:
        registry = yaml.safe_load(f)
    registry["current_phase"] = "phase_01_research"
    for track in registry["tracks"]:
        if track["id"] == "research_strategy_momentum":
            track["state"] = "ACTIVE"
            track["experiments"] = 1
    with open(reg, "w") as f:
        yaml.dump(registry, f, allow_unicode=True)

    track_dir = project_dir / "prae" / "phases" / "phase_01_research" / "tracks" / "research_strategy_momentum"
    track_dir.mkdir(parents=True, exist_ok=True)
    (track_dir / "TRACK_LOG.md").write_text(
        "# TRACK_LOG\n\n**Research Cycle**: cycle_1\n\n## Experiments\n\n| EXP_001 | 2026-04-20 | test | ok | [EXP_001.md](experiments/EXP_001.md) |\n"
        "\n## Evidence Summary\n\n- 2026-04-20 EXP_001: positive signal\n"
        "\n## Decision Log\n\n| 2026-04-20 | EXPLORING → ACTIVE | AI | maintainer | EXP_001 signal positive |\n"
    )

    if not with_research_artifacts:
        return

    exp_dir = track_dir / "experiments"
    exp_dir.mkdir(parents=True, exist_ok=True)
    (exp_dir / "EXP_001.md").write_text(
        "# EXP_001\n\n## Goal\nTest the momentum factor\n\n## Method\n"
        "- Data Source: infra_data_v1.load_daily_bars\n"
        "- Time Window: 2020-01-01 to 2023-12-31\n"
        "- Random Seed: seed=42\n"
        "- Control Group: no control group\n\n"
        "## Preflight Check\n"
        "**Minimal Smoke Check**: finishes within 30s and prints sharpe\n\n"
        "**Output Contract**: stdout contains at least sharpe\n\n"
        "**Out of Scope This Time**: no abstraction into impl/\n\n"
        "## Expected Signal\nsharpe>1.0\n\n"
        "## Result\nsharpe: 1.2\n\n## Conclusion\n**Conclusion**: supports the hypothesis\n"
    )

    py_dir = project_dir / "src" / "tracks" / "research_strategy_momentum" / "experiments"
    py_dir.mkdir(parents=True, exist_ok=True)
    (py_dir / "EXP_001.py").write_text(
        "def main():\n    print('ok')\n\nif __name__ == '__main__':\n    main()\n"
    )


def make_phase2_graduated_track(project_dir: Path) -> None:
    import yaml

    reg = project_dir / "prae" / "track_registry.yaml"
    with open(reg) as f:
        registry = yaml.safe_load(f)
    registry["current_phase"] = "phase_02_validation"
    for track in registry["tracks"]:
        if track["id"] == "research_strategy_momentum":
            track["state"] = "GRADUATED"
            track["experiments"] = 1
            track["concluded_at"] = "2026-04-20"
    with open(reg, "w") as f:
        yaml.dump(registry, f, allow_unicode=True)

    track_dir = project_dir / "prae" / "phases" / "phase_02_validation" / "tracks" / "research_strategy_momentum"
    track_dir.mkdir(parents=True, exist_ok=True)
    (track_dir / "TRACK_LOG.md").write_text(
        "# TRACK_LOG\n\n**Research Cycle**: cycle_1\n\n## Experiments\n\n| EXP_001 | 2026-04-20 | test | graduated | [EXP_001.md](experiments/EXP_001.md) |\n"
        "\n## Evidence Summary\n\n- 2026-04-20 EXP_001: positive signal\n"
        "\n## Final Conclusion\n\nGRADUATED — signal is stable, handed off to PDAE.\n"
    )

    exp_dir = track_dir / "experiments"
    exp_dir.mkdir(parents=True, exist_ok=True)
    (exp_dir / "EXP_001.md").write_text(
        "# EXP_001\n\n## Goal\nValidate the momentum factor\n\n## Method\n"
        "- Data Source: infra_data_v1.load_daily_bars\n"
        "- Time Window: 2020-01-01 to 2023-12-31\n"
        "- Random Seed: seed=42\n"
        "- Control Group: no control group\n\n"
        "## Preflight Check\n"
        "**Minimal Smoke Check**: finishes within 30s and prints sharpe\n\n"
        "**Output Contract**: stdout contains at least sharpe\n\n"
        "**Out of Scope This Time**: no abstraction into impl/\n\n"
        "## Expected Signal\nsharpe>1.0\n\n"
        "## Result\nsharpe: 1.2\n\n## Conclusion\n**Conclusion**: supports the hypothesis\n"
    )

    py_dir = project_dir / "src" / "tracks" / "research_strategy_momentum" / "experiments"
    py_dir.mkdir(parents=True, exist_ok=True)
    (py_dir / "EXP_001.py").write_text(
        "def main():\n    print('validated')\n\nif __name__ == '__main__':\n    main()\n"
    )


class TestPhaseGate0to1:
    def test_exploring_infra_fails(self, fake_project):
        rc, out = run_tool(str(fake_project), ["--phase", "0"])
        assert rc == 1
        assert out["passed"] is False

    def test_locked_infra_passes(self, locked_infra_project):
        rc, out = run_tool(str(locked_infra_project), ["--phase", "0"])
        assert rc == 0
        assert out["passed"] is True

    def test_missing_registry_is_error(self, tmp_path):
        rc, out = run_tool(str(tmp_path), ["--phase", "0"])
        assert rc == 2

    def test_override_blocks_regular_phase_gate(self, fake_project):
        set_phase_override(fake_project, "phase_00_infra")

        rc, out = run_tool(str(fake_project))

        assert rc == 2, out
        assert "current_phase_override" in out.get("summary", out.get("stderr", ""))


class TestPhaseGate1to2:
    def test_no_active_fails(self, fake_project):
        rc, out = run_tool(str(fake_project), ["--phase", "1"])
        assert rc == 1
        assert out["passed"] is False

    def test_with_active_track_passes(self, fake_project):
        make_phase1_active_track(fake_project, with_research_artifacts=True)
        rc, out = run_tool(str(fake_project), ["--phase", "1"])
        assert rc == 0
        assert out["passed"] is True

    def test_active_track_without_research_gate_fails(self, fake_project):
        make_phase1_active_track(fake_project, with_research_artifacts=False)
        rc, out = run_tool(str(fake_project), ["--phase", "1"])
        assert rc == 1
        assert out["passed"] is False


class TestPhaseGate2to3:
    def _make_phase2_project(self, fake_project):
        import yaml
        reg = fake_project / "prae" / "track_registry.yaml"
        with open(reg) as f:
            r = yaml.safe_load(f)
        r["current_phase"] = "phase_02_validation"
        for t in r["tracks"]:
            if t["id"] == "research_strategy_momentum":
                t["state"] = "GRADUATED"
                t["concluded_at"] = "2026-04-20"
        with open(reg, "w") as f:
            yaml.dump(r, f, allow_unicode=True)
        return fake_project

    def test_active_track_remaining_fails(self, fake_project):
        import yaml
        reg = fake_project / "prae" / "track_registry.yaml"
        with open(reg) as f:
            r = yaml.safe_load(f)
        r["current_phase"] = "phase_02_validation"
        for t in r["tracks"]:
            if t["id"] == "research_strategy_momentum":
                t["state"] = "ACTIVE"
        with open(reg, "w") as f:
            yaml.dump(r, f, allow_unicode=True)
        rc, out = run_tool(str(fake_project), ["--phase", "2"])
        assert rc == 1
        assert out["passed"] is False

    def test_no_graduated_fails(self, fake_project):
        import yaml
        reg = fake_project / "prae" / "track_registry.yaml"
        with open(reg) as f:
            r = yaml.safe_load(f)
        r["current_phase"] = "phase_02_validation"
        for t in r["tracks"]:
            if t["id"] == "research_strategy_momentum":
                t["state"] = "KILLED"
                t["concluded_at"] = "2026-04-20"
        with open(reg, "w") as f:
            yaml.dump(r, f, allow_unicode=True)
        rc, out = run_tool(str(fake_project), ["--phase", "2"])
        assert rc == 1
        assert out["passed"] is False

    def test_graduated_with_no_active_passes(self, fake_project):
        make_phase2_graduated_track(fake_project)
        rc, out = run_tool(str(fake_project), ["--phase", "2"])
        assert rc == 0
        assert out["passed"] is True


class TestCheckApproved:
    def test_pending_approval_fails(self, fake_project):
        gate_dir = fake_project / "prae" / "phases" / "phase_00_infra"
        gate_dir.mkdir(parents=True, exist_ok=True)
        (gate_dir / "PHASE_GATE.md").write_text(
            make_valid_phase_gate_doc(0, 1, "phase_01_research", "pending")
        )
        rc, out = run_tool(str(fake_project), ["--check-approved"])
        assert rc == 1

    def test_yes_approval_passes(self, locked_infra_project):
        gate_dir = locked_infra_project / "prae" / "phases" / "phase_00_infra"
        gate_dir.mkdir(parents=True, exist_ok=True)
        (gate_dir / "PHASE_GATE.md").write_text(
            make_valid_phase_gate_doc(0, 1, "phase_01_research", "yes")
        )
        rc, out = run_tool(str(locked_infra_project), ["--check-approved"])
        assert rc == 0

    def test_phase1_specific_checklist_passes(self, fake_project):
        make_phase1_active_track(fake_project, with_research_artifacts=True)
        set_current_phase(fake_project, "phase_01_research")
        gate_dir = fake_project / "prae" / "phases" / "phase_01_research"
        gate_dir.mkdir(parents=True, exist_ok=True)
        (gate_dir / "PHASE_GATE.md").write_text(
            make_valid_phase_gate_doc(1, 2, "phase_02_validation", "yes")
        )
        rc, out = run_tool(str(fake_project), ["--check-approved"])
        assert rc == 0
        assert out["passed"] is True

    def test_phase2_specific_checklist_passes(self, fake_project):
        make_phase2_graduated_track(fake_project)
        set_current_phase(fake_project, "phase_02_validation")
        gate_dir = fake_project / "prae" / "phases" / "phase_02_validation"
        gate_dir.mkdir(parents=True, exist_ok=True)
        (gate_dir / "PHASE_GATE.md").write_text(
            make_valid_phase_gate_doc(2, 3, "phase_03_conclusion", "yes")
        )
        rc, out = run_tool(str(fake_project), ["--check-approved"])
        assert rc == 0
        assert out["passed"] is True

    def test_invalid_structure_fails_even_if_approved(self, fake_project):
        gate_dir = fake_project / "prae" / "phases" / "phase_00_infra"
        gate_dir.mkdir(parents=True, exist_ok=True)
        (gate_dir / "PHASE_GATE.md").write_text(
            "# Gate\n\nAPPROVED: yes\nAPPROVER: maintainer\nAPPROVED_AT: 2026-04-20\n"
        )
        rc, out = run_tool(str(fake_project), ["--check-approved"])
        assert rc == 1
        assert out["passed"] is False

    def test_missing_phase_specific_checklist_fails(self, locked_infra_project):
        gate_dir = locked_infra_project / "prae" / "phases" / "phase_00_infra"
        gate_dir.mkdir(parents=True, exist_ok=True)
        (gate_dir / "PHASE_GATE.md").write_text(
            make_valid_phase_gate_doc(
                0,
                1,
                "phase_01_research",
                "yes",
                drop_checklist_item="check_contracts.py passes for all infrastructure contracts",
            )
        )
        rc, out = run_tool(str(locked_infra_project), ["--check-approved"])
        assert rc == 1
        assert out["passed"] is False

    def test_checkbox_mismatch_with_actual_gate_fails(self, locked_infra_project):
        gate_dir = locked_infra_project / "prae" / "phases" / "phase_00_infra"
        gate_dir.mkdir(parents=True, exist_ok=True)
        (gate_dir / "PHASE_GATE.md").write_text(
            make_valid_phase_gate_doc(
                0,
                1,
                "phase_01_research",
                "yes",
                unchecked_items={"Every LOCKED track has MODULE_SPEC.md"},
            )
        )
        rc, out = run_tool(str(locked_infra_project), ["--check-approved"])
        assert rc == 1
        assert out["passed"] is False

    def test_wrong_cycle_fails_even_if_approved(self, locked_infra_project):
        gate_dir = locked_infra_project / "prae" / "phases" / "phase_00_infra"
        gate_dir.mkdir(parents=True, exist_ok=True)
        (gate_dir / "PHASE_GATE.md").write_text(
            make_valid_phase_gate_doc(0, 1, "phase_01_research", "yes", cycle_label="cycle_2")
        )
        rc, out = run_tool(str(locked_infra_project), ["--check-approved"])
        assert rc == 1
        assert out["passed"] is False
